version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  test:
    docker:
      - image: circleci/python:3.8.5
        environment:
          DATABASE_URL: postgresql://circleci@localhost:5432/circle_test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          cache-version: v2
          include-python-in-cache-key: false
      - run:
          name: Test
          command: poetry run pytest
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
