version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2
  python: circleci/python@1.2.0

workflows:
  main:
    jobs:
      - python/test:
          name: test
          docker:
          - image: circleci/postgres:12.4-alpine
            environment:
              POSTGRES_USER: circleci
              POSTGRES_DB: circle_test
          pkg-manager: poetry
          test-tool: pytest
          version: 3.8.5
      - heroku/deploy-via-git:
          name: deploy
          requires:
            - test
          filters:
            branches:
              only: master
