# Generated by Django 3.0.8 on 2020-08-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0004_auto_20200802_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('jack', 'Jack'), ('queen', 'Queen'), ('king', 'King'), ('ace', 'Ace')], editable=False, max_length=10)),
                ('suit', models.CharField(choices=[('hearts', 'Hearts'), ('clubs', 'Clubs'), ('diamonds', 'Diamonds'), ('spades', 'Spades')], editable=False, max_length=10)),
            ],
        ),
    ]
