# Generated by Django 3.0.8 on 2020-08-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0005_card'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('rank', 'suit')},
        ),
        migrations.CreateModel(
            name='DrawCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_key', models.PositiveIntegerField(unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='durak.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_pile', to='durak.Game')),
            ],
            options={
                'ordering': ['sort_key'],
            },
        ),
    ]
