# Generated by Django 3.0.8 on 2020-08-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0006_auto_20200804_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawcard',
            options={'ordering': ['game', 'sort_key']},
        ),
        migrations.AlterField(
            model_name='drawcard',
            name='sort_key',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='drawcard',
            unique_together={('game', 'sort_key')},
        ),
    ]
