# Generated by Django 3.0.8 on 2020-08-17 01:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('durak', '0007_auto_20200804_0257'), ('durak', '0008_event_result'), ('durak', '0009_auto_20200816_1523')]

    dependencies = [
        ('durak', '0006_auto_20200804_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawcard',
            options={'ordering': ['game', 'sort_key']},
        ),
        migrations.AlterField(
            model_name='drawcard',
            name='sort_key',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='drawcard',
            unique_together={('game', 'sort_key')},
        ),
        migrations.AddField(
            model_name='event',
            name='to_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
