# Generated by Django 3.0.8 on 2020-09-03 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0008_event_to_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_rank', models.CharField(choices=[('2', 'Two'), ('6', 'Six')], default='6', max_length=10)),
                ('attack_limit', models.IntegerField(choices=[(6, 'Standard'), (100, 'Unlimited')], default=6)),
                ('with_passing', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('lowest_rank', 'attack_limit', 'with_passing')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='durak.GameVariant'),
        ),
    ]
