# Generated by Django 3.0.8 on 2020-08-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0008_event_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='result',
            new_name='to_state',
        ),
    ]
