# Generated by Django 3.0.8 on 2020-08-16 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0009_auto_20200816_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='to_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
