# Generated by Django 3.0.8 on 2020-09-05 03:16

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Game = apps.get_model("durak", "Game")
    GameVariant = apps.get_model("durak", "GameVariant")

    variant, _ = GameVariant.objects.get_or_create(
        lowest_rank="6", attack_limit=6, with_passing=True
    )
    Game.objects.all().update(variant=variant)


class Migration(migrations.Migration):

    dependencies = [
        ("durak", "0009_auto_20200903_0210"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="game",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="durak.GameVariant"
            ),
        ),
    ]
