# Generated by Django 3.0.8 on 2020-09-08 12:34

from django.db import migrations, models
from random import random


def forwards(apps, schema_editor):
    Game = apps.get_model("durak", "Game")
    for game in Game.objects.all():
        game.seed = random()
        game.save()
        game.event_set.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0010_auto_20200905_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seed',
            field=models.DecimalField(decimal_places=10, default=0.1, max_digits=10),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
