# Generated by Django 3.0.8 on 2020-09-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durak', '0014_gamerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequest',
            old_name='users',
            new_name='players',
        ),
    ]
