# Generated by Django 3.0.8 on 2020-10-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("durak", "0015_game_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
