# Generated by Django 3.0.8 on 2020-11-13 20:56

from django.db import migrations, models


def forwards(apps, schema_editor):
    GameVariant = apps.get_model("durak", "GameVariant")
    for variant in GameVariant.objects.all():
        if variant.attack_limit_old == 6:
            variant.attack_limit = "six"
        elif variant.attack_limit_old == 100:
            variant.attack_limit = "hand"
        variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("durak", "0016_event_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamevariant",
            name="attack_limit_old",
            field=models.IntegerField(
                choices=[(6, "Standard"), (100, "Unlimited")], default=6
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="gamevariant",
            name="attack_limit",
            field=models.CharField(
                choices=[("six", "Six"), ("hand", "Hand"), ("unlimited", "Unlimited")],
                default="six",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamevariant",
            unique_together={
                ("lowest_rank", "attack_limit_old", "attack_limit", "with_passing")
            },
        ),
    ]
