# Generated by Django 3.0.8 on 2020-11-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("durak", "0017_auto_20201113_2056"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gamevariant",
            unique_together={("lowest_rank", "attack_limit", "with_passing")},
        ),
        migrations.RemoveField(
            model_name="gamevariant",
            name="attack_limit_old",
        ),
    ]
